"""Write docs/COMPONENTS-REFERENCE.md from what the Code tab prints.

python3 qa/reference.py           write docs/COMPONENTS-REFERENCE.md
python3 qa/reference.py --check   build it in memory and compare with the file on
                                  disk. Exits 1 and says so when they differ, so a
                                  stale reference cannot be committed.

It opens index.html from file:// (1440x900, dark, reduced motion, so nothing
random is on screen), goes to Components and, for every component section in
page order, opens its Code tab and reads:
  group      data-group, set by the docs builder from KIT_GROUPS (js/30)
  id         the section's aria-labelledby, and its address #components/NAME
  kit        whether kit/starter.html has it (section#NAME). Command and
             Picture are site only
  caption    the first p.muted of the section
  html       the Code tab html, exactly as printed
  behaviors  the data-aui names and data-aui-* attributes the js part lists
  css        the kit css block names the css part prints (the base blocks,
             tokens, tones, base and frame, are in every page and never printed)
  notes      the comment lines the js part opens with when the kit cannot run
             the demo as it is on the site (js/40, SITEONLY)
Get the kit (s-install), Rules (s-rules) and Foundations (s-foundations) are not
components and are left out.
"""
import os,re,sys
from playwright.sync_api import sync_playwright

ROOT=os.path.abspath(os.path.join(os.path.dirname(__file__),'..'))
OUT=os.path.join(ROOT,'docs','COMPONENTS-REFERENCE.md')
STARTER=os.path.join(ROOT,'kit','starter.html')
SKIP=('s-install','s-rules','s-foundations')

READ="""()=>[...document.querySelectorAll('#view-kit > section[aria-labelledby]')].map(s=>{
  const id=s.getAttribute('aria-labelledby');
  const cap=s.querySelector(':scope > p.muted:not(.status)');
  const t=s.querySelectorAll('.doc-tabs .tab')[1];if(t)t.click();
  const part=n=>{const e=s.querySelector('[data-part='+n+']');return e?e.textContent:''};
  return {id:id,name:s.querySelector('h2').textContent.trim(),group:s.dataset.group||'',
    caption:cap?cap.textContent.replace(/\\s+/g,' ').trim():'',html:part('html'),css:part('css'),js:part('js')};
})"""

def kit_parts():
    src=open(STARTER,encoding='utf-8').read()
    return set(re.findall(r'<section class="part" id="([a-z0-9-]+)"',src))

def harvest():
    errs=[]
    with sync_playwright() as p:
        b=p.chromium.launch()
        pg=b.new_page(viewport={'width':1440,'height':900},color_scheme='dark',reduced_motion='reduce')
        pg.on('pageerror',lambda e:errs.append(str(e)))
        pg.goto('file://'+os.path.join(ROOT,'index.html'))
        pg.wait_for_timeout(1500)
        pg.evaluate("document.getElementById('v-kit').click()")
        pg.wait_for_timeout(800)
        rows=pg.evaluate(READ)
        b.close()
    if errs: sys.exit('reference: page errors: '+'; '.join(errs))
    return [r for r in rows if r['id'] not in SKIP]

def behaviors(js):
    names=re.findall(r'^// data-aui="([a-z-]+)"  (.*)$',js,re.M)
    attrs=re.findall(r'^// (data-aui-[a-z-]+)  (.*)$',js,re.M)
    return names,attrs

def notes(js):
    out=[]
    for line in js.splitlines():
        if not line.startswith('// '): break
        t=line[3:]
        if t.startswith('ascii-ui.js runs') or t.startswith('none.') or t.startswith('data-aui'): break
        out.append(t)
    return out

def md(t):
    # prose goes into markdown as text: an <img> in a note is a word, not a tag
    return t.replace('&','&amp;').replace('<','&lt;').replace('>','&gt;')

def render(rows):
    kit=kit_parts()
    o=['# Components reference','',
       'Generated by `python3 qa/reference.py` from what the Code tab prints. Do not edit by hand: change the component, then run it again. `python3 qa/reference.py --check` fails when this file is stale, and `qa/release.sh` runs that check.','',
       'One entry per component, in page order (group, then name). "Kit" means the component is in `kit/starter.html` and works with the two kit files as printed. "Site only" means it needs this site\'s engine. The html is exactly what the Code tab prints: no ids, the kit\'s `data-aui` attributes, safe to paste twice. CSS blocks are the `/* ==== name: selectors ==== */` blocks of `kit/ascii-ui.css` that the Code tab prints for it; `tokens`, `tones`, `base` and `frame` are in every page and never listed. Behaviors are the `behaviors.NAME` functions of `kit/ascii-ui.js` and the button attributes it handles. How to add a component: `docs/COMPONENTS.md`.','']
    ins=sum(1 for r in rows if r['id'][2:] in kit)
    o+=['%d components: %d in the kit, %d site only.'%(len(rows),ins,len(rows)-ins),'',
        '| Component | Group | Id | Kit | Behaviors | CSS blocks |','|---|---|---|---|---|---|']
    for r in rows:
        n,a=behaviors(r['js'])
        blocks=re.findall(r'^/\* ==== ([a-z-]+): ',r['css'],re.M)
        beh=', '.join(['`'+x[0]+'`' for x in n]+['`'+x[0]+'`' for x in a]) or 'none'
        o.append('| [%s](#%s) | %s | `%s` | %s | %s | %s |'%(r['name'],r['id'],r['group'],r['id'],
                 'yes' if r['id'][2:] in kit else 'site only',beh,', '.join('`'+x+'`' for x in blocks) or 'none'))
    o.append('')
    group=None
    for r in rows:
        if r['group']!=group:
            group=r['group'];o+=['## '+group,'']
        n,a=behaviors(r['js'])
        blocks=re.findall(r'^/\* ==== ([a-z-]+): (.+?) ==== \*/$',r['css'],re.M)
        o+=['<a id="%s"></a>'%r['id'],'### '+r['name'],'',
            '- Id: `%s`, address `#components/%s`'%(r['id'],r['id'][2:]),
            '- Group: '+r['group'],
            '- In the kit: '+('yes, `kit/starter.html#%s`'%r['id'][2:] if r['id'][2:] in kit else 'no, site only'),
            '- Caption: '+md(r['caption'])]
        for t in notes(r['js']): o.append('- Note: '+md(t))
        if n or a:
            o.append('- Behaviors:')
            for x in n: o.append('  - `data-aui="%s"`: %s'%(x[0],md(x[1])))
            for x in a: o.append('  - `%s`: %s'%(x[0],md(x[1])))
        else: o.append('- Behaviors: none, HTML and CSS only')
        if blocks:
            o.append('- CSS blocks:')
            for b in blocks: o.append('  - `%s`: `%s`'%b)
        else: o.append('- CSS blocks: none beyond the base')
        o+=['','```html',r['html'].rstrip('\n'),'```','']
    return '\n'.join(o).rstrip('\n')+'\n'

def main():
    check='--check' in sys.argv[1:]
    text=render(harvest())
    if check:
        have=open(OUT,encoding='utf-8').read() if os.path.exists(OUT) else ''
        if have!=text:
            print('reference --check: docs/COMPONENTS-REFERENCE.md is stale, run python3 qa/reference.py and commit it')
            sys.exit(1)
        print('reference --check: ok')
        return
    open(OUT,'w',encoding='utf-8').write(text)
    print('docs/COMPONENTS-REFERENCE.md: %d lines'%text.count('\n'))

if __name__=='__main__':
    main()
